In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv('bank.csv')
dataset

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [4]:
a=dataset.drop(['contact','day','month','duration','campaign','pdays','previous','poutcome','default'],axis=1)
a

age          job  marital  education  balance housing loan deposit
0       59       admin.  married  secondary     2343     yes   no     yes
1       56       admin.  married  secondary       45      no   no     yes
2       41   technician  married  secondary     1270     yes   no     yes
3       55     services  married  secondary     2476     yes   no     yes
4       54       admin.  married   tertiary      184      no   no     yes
...    ...          ...      ...        ...      ...     ...  ...     ...
11157   33  blue-collar   single    primary        1     yes   no      no
11158   39     services  married  secondary      733      no   no      no
11159   32   technician   single  secondary       29      no   no      no
11160   43   technician  married  secondary        0      no  yes      no
11161   34   technician  married  secondary        0      no   no      no

[11162 rows x 8 columns]

In [5]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [6]:
dataset['deposit']=lb.fit_transform(dataset['deposit'])
dataset['housing']=lb.fit_transform(dataset['housing'])
dataset['loan']=lb.fit_transform(dataset['loan'])
dataset['marital']=lb.fit_transform(dataset['marital'])
dataset['job']=lb.fit_transform(dataset['job'])
dataset['education']=lb.fit_transform(dataset['education'])


In [7]:
a=dataset.drop(['contact','day','month','duration','campaign','pdays','previous','poutcome','default'],axis=1)
a

age  job  marital  education  balance  housing  loan  deposit
0       59    0        1          1     2343        1     0        1
1       56    0        1          1       45        0     0        1
2       41    9        1          1     1270        1     0        1
3       55    7        1          1     2476        1     0        1
4       54    0        1          2      184        0     0        1
...    ...  ...      ...        ...      ...      ...   ...      ...
11157   33    1        2          0        1        1     0        0
11158   39    7        1          1      733        0     0        0
11159   32    9        2          1       29        0     0        0
11160   43    9        1          1        0        0     1        0
11161   34    9        1          1        0        0     0        0

[11162 rows x 8 columns]

In [8]:
x=a.iloc[:,:7].values
x

array([[  59,    0,    1, ..., 2343,    1,    0],
       [  56,    0,    1, ...,   45,    0,    0],
       [  41,    9,    1, ..., 1270,    1,    0],
       ...,
       [  32,    9,    2, ...,   29,    0,    0],
       [  43,    9,    1, ...,    0,    0,    1],
       [  34,    9,    1, ...,    0,    0,    0]], dtype=int64)

In [9]:
dataset['housing']=lb.fit_transform(dataset['housing'])

In [10]:
y=a.iloc[:,7:8].values
y

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [12]:
from sklearn.linear_model import LinearRegression
mr=LinearRegression()

In [13]:
mr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
from joblib import dump
dump(lb,"project1.save")

['project1.save']

In [15]:
from sklearn.tree import DecisionTreeRegressor 

In [16]:
dt=DecisionTreeRegressor ( random_state=0)

In [17]:
dt.fit(x_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [18]:
y_pred=dt.predict(x_test)
y_pred

array([1., 0., 0., ..., 0., 0., 0.])

In [19]:
import pickle
pickle.dump(dt,open('project1.pkl','wb'))

In [21]:
dt.predict([[1,1,1,1,1,1,1,
            
            ]])

ValueError: Number of features of the model must match the input. Model n_features is 7 and input n_features is 8 